### ISSUE TITLE
Secret doors

### ISSUE THREAD

**Issue by davidk64fnq** [snafaru/Wizardry.Code#1]
Thanks for the work you are doing on this! One thing I wonder about is secret doors. Since there is Milwa and Lomilwa to reveal secret doors I imagine that you can never see secret doors unless those spells are in effect. Yet in practice you do randomly see secret doors -  intermittently. Do you think this is the intention on the part of the game designers? Is there an argument for modifying the code to not reveal secret doors ever unless a light spell is in effect?

Edit: I came across on page 28 of Apple manual "Also, be aware that there are secret doors which you rarely see, ..." so I guess that answers the question. It is intended to randomly see secret doors without the aid of light spell.

**Comment by snafaru** [comment]
The programmers intentionally made the code show the secret doors from time to time.
