### ISSUE TITLE
Message too quick on level 1?

### ISSUE THREAD

**Issue by davidk64fnq** [snafaru/Wizardry.Code#2]
When I enter the room where man in robes teleports me to castle I read the description of the man in robes then press return and immediately get teleported without a chance to read the rest of the message. I tried setting time delay to 5000 but didn't make any difference. Is there supposed to be a press return prompt after second message displayed so I can read it before the teleport happens?

**Comment by snafaru** [comment]
Hi David.

This is on level 1 and it had me wondering for years what it was when I was playing when I was a teenager.

If you are using an emulator you may be able to see the message if you slow it down.

I noted your observation, and I will introduce a delay there in my list of things to fix.

Thanks for communicating this with me.

Eric

The message is:

A STRANGE GLOW SEEMS TO EMANATE FROM
THIS ROOM.  IN THE CENTER, A SMALLISH
MAN IN A LONG ROBE TURNS TOWARDS THE
PARTY AND SHOUTS,
   "BEGONE, STRANGERS!"
HE THEN BEGINS WAVING HIS HANDS, AND
INTONES THE WORDS,
   "MAPIRO MAHAMA DIROMAT"
